version: '2'
services:
    dormitoryservice-app:
        image: dormitoryservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dormitoryservice-postgresql:5432/DormitoryService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dormitoryservice-postgresql:
        extends:
            file: postgresql.yml
            service: dormitoryservice-postgresql
